// user actions
export const GET_USER_PENDING = 'GET_USER_PENDING';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILED = 'GET_USER_FAILED';

export const ADD_USER_PENDING = 'ADD_USER_PENDING';
export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
export const ADD_USER_FAILED = 'ADD_USER_FAILED';

export const GET_ALL_USER_PENDING = 'GET_ALL_USER_PENDING';
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS';
export const GET_ALL_USER_FAILED = 'GET_ALL_USER_FAILED';


// party
export const GET_ALL_PARTY_PENDING = 'GET_ALL_PARTY_PENDING';
export const GET_ALL_PARTY_SUCCESS = 'GET_ALL_PARTY_SUCCESS';
export const GET_ALL_PARTY_FAILED = 'GET_ALL_PARTY_FAILED';

export const ADD_PARTY_PENDING = 'ADD_PARTY_PENDING';
export const ADD_PARTY_SUCCESS = 'ADD_PARTY_SUCCESS';
export const ADD_PARTY_FAILED = 'ADD_PARTY_FAILED';

export const DELETE_PARTY_PENDING = 'DELETE_PARTY_PENDING';
export const DELETE_PARTY_SUCCESS = 'DELETE_PARTY_SUCCESS';
export const DELETE_PARTY_FAILED = 'DELETE_PARTY_FAILED';


// election 

export const GET_ALL_ELECTION_PENDING = 'GET_ALL_ELECTION_PENDING';
export const GET_ALL_ELECTION_SUCCESS = 'GET_ALL_ELECTION_SUCCESS';
export const GET_ALL_ELECTION_FAILED = 'GET_ALL_ELECTION_FAILED';

export const ADD_ELECTION_PENDING = 'ADD_ELECTION_PENDING';
export const ADD_ELECTION_SUCCESS = 'ADD_ELECTION_SUCCESS';
export const ADD_ELECTION_FAILED = 'ADD_ELECTION_FAILED';

// connection 

export const GET_ALL_CONNECTION_PENDING = 'GET_ALL_CONNECTION_PENDING';
export const GET_ALL_CONNECTION_SUCCESS = 'GET_ALL_CONNECTION_SUCCESS';
export const GET_ALL_CONNECTION_FAILED = 'GET_ALL_CONNECTION_FAILED';

export const ADD_CONNECTION_PENDING = 'ADD_CONNECTION_PENDING';
export const ADD_CONNECTION_SUCCESS = 'ADD_CONNECTION_SUCCESS';
export const ADD_CONNECTION_FAILED = 'ADD_CONNECTION_FAILED';


// vote

export const GET_ALL_VOTE_PENDING = 'GET_ALL_VOTE_PENDING';
export const GET_ALL_VOTE_SUCCESS = 'GET_ALL_VOTE_SUCCESS';
export const GET_ALL_VOTE_FAILED = 'GET_ALL_VOTE_FAILED';

export const ADD_VOTE_PENDING = 'ADD_VOTE_PENDING';
export const ADD_VOTE_SUCCESS = 'ADD_VOTE_SUCCESS';
export const ADD_VOTE_FAILED = 'ADD_VOTE_FAILED';



